services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:${LOCAL_WORKSPACE_FOLDER}:cached
  hass:
    extends:
      file: .devcontainer/frigate-hass-integration/docker-compose.yml
      service: hass
    volumes:
      - .devcontainer/preconfig:/preconfig.d/02-card:ro
  frigate:
    extends:
      file: .devcontainer/frigate-hass-integration/docker-compose.yml
      service: frigate
  mqtt:
    extends:
      file: .devcontainer/frigate-hass-integration/docker-compose.yml
      service: mqtt
